import {
  WhatsApp,
  Twitter,
  Instagram,
  Spotify,
  Linkedin,
  Youtube,
  Google,
  Facebook,
  CodeWave,
  User1,
  User2,
  User3,
  User4,
  User5,
  User6,
  User7,
  User8,
  User9,
} from "../assets";

export const jobTypes = ["Full-Time", "Part-Time", "ContracT", "Intern"];

export const experience = [
  { title: "Under 1000", value: "0-1000" },
  { title: "1000 - 2000", value: "1000-2000" },
  { title: "2000 -5000", value: "2000-5000" },
  { title: "Over 5000", value: "5000-100000" },
];

export const popularSearch = [
  "Software Engineer",
  "Developer",
  "Full-Stack Developer",
  "Data Scientist",
  "Remote",
  "Full-Time",
  "Sales",
  "Office Assistant",
];

export const jobs = [
  {
    projectTitle: "Blog Website",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "1200",
    desc: "A blog website where users can create, read, update, and delete blog posts. Includes user authentication and comment functionality.",
  },
  {
    projectTitle: "Weather App",
    techMat: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
    tags: ["Front End"],
    sellingAmount: "800",
    desc: "A weather application that fetches weather data from an API and displays it to users. Users can search for weather information based on location.",
  },
  {
    projectTitle: "Task Management System",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "1600",
    desc: "A task management system where users can create, update, and delete tasks. Includes features such as task categorization and priority.",
  },
  {
    projectTitle: "Social Media Analytics Dashboard",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Python",
      "Flask",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "2500",
    desc: "A dashboard that provides analytics and insights for social media platforms. Includes features such as user engagement metrics and sentiment analysis.",
  },
  {
    projectTitle: "Recipe Sharing Platform",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "1400",
    desc: "A platform for sharing and discovering recipes. Users can create, share, and rate recipes. Includes search and filter functionality.",
  },
  {
    projectTitle: "Online Learning Platform",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "2000",
    desc: "An online learning platform where users can access courses, quizzes, and assignments. Includes user progress tracking and course recommendations.",
  },
  {
    projectTitle: "Event Management System",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "1800",
    desc: "A system for organizing and managing events. Includes features such as event scheduling, registration, and attendee management.",
  },
  {
    projectTitle: "Inventory Management System",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "1700",
    desc: "A system for managing inventory and stock levels. Includes features such as product categorization, stock alerts, and sales reporting.",
  },
  {
    projectTitle: "Finance Tracker App",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "2200",
    desc: "An application for tracking personal finances. Users can manage expenses, set budgets, and view spending trends.",
  },
  {
    projectTitle: "Chat Application",
    techMat: ["HTML", "CSS", "JavaScript", "React", "Node.js", "Socket.io"],
    tags: ["Full Stack", "Front End", "Back End"],
    sellingAmount: "1000",
    desc: "A real-time chat application that allows users to communicate with each other. Supports private and group chats.",
  },
  {
    projectTitle: "Fitness Tracking App",
    techMat: ["HTML", "CSS", "JavaScript", "React Native", "Firebase"],
    tags: ["Mobile App", "Front End", "Database"],
    sellingAmount: "900",
    desc: "An app for tracking fitness activities such as workouts, calorie intake, and weight management. Includes features like goal setting and progress tracking.",
  },
  {
    projectTitle: "Music Streaming Service",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "2800",
    desc: "A platform for streaming music online. Users can listen to songs, create playlists, and follow artists. Includes features such as personalized recommendations.",
  },
  {
    projectTitle: "Recipe Management App",
    techMat: ["HTML", "CSS", "JavaScript", "React Native", "Firebase"],
    tags: ["Mobile App", "Front End", "Database"],
    sellingAmount: "1000",
    desc: "An app for organizing and managing recipes. Users can add, edit, and categorize recipes. Includes features like ingredient shopping lists.",
  },
  {
    projectTitle: "Job Search Platform",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "2000",
    desc: "A platform for job seekers to search and apply for job listings. Includes features such as resume uploading and job alerts.",
  },
  {
    projectTitle: "Language Learning App",
    techMat: ["HTML", "CSS", "JavaScript", "React Native", "Firebase"],
    tags: ["Mobile App", "Front End", "Database"],
    sellingAmount: "1100",
    desc: "An app for learning new languages through interactive lessons and quizzes. Supports multiple languages and proficiency levels.",
  },
  {
    projectTitle: "Restaurant Booking System",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "1900",
    desc: "A system for making restaurant reservations online. Users can search for restaurants, view menus, and book tables.",
  },
  {
    projectTitle: "Travel Planner App",
    techMat: ["HTML", "CSS", "JavaScript", "React Native", "Firebase"],
    tags: ["Mobile App", "Front End", "Database"],
    sellingAmount: "1200",
    desc: "An app for planning and organizing travel itineraries. Users can search for destinations, book flights and accommodations, and create trip schedules.",
  },
  {
    projectTitle: "Budget Tracking App",
    techMat: ["HTML", "CSS", "JavaScript", "React Native", "Firebase"],
    tags: ["Mobile App", "Front End", "Database"],
    sellingAmount: "950",
    desc: "An app for tracking personal finances and expenses. Users can set budgets, categorize transactions, and visualize spending habits.",
  },
  {
    projectTitle: "Car Rental System",
    techMat: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    tags: ["Full Stack", "Front End", "Back End", "Database"],
    sellingAmount: "2200",
    desc: "A system for renting cars online. Users can search for available vehicles, make reservations, and manage bookings.",
  },
  {
    projectTitle: "Task Timer App",
    techMat: ["HTML", "CSS", "JavaScript", "React Native", "Firebase"],
    tags: ["Mobile App", "Front End", "Database"],
    sellingAmount: "800",
    desc: "An app for tracking time spent on tasks and projects. Users can set timers, record activities, and generate reports.",
  },
];

export const footerLinks = [
  {
    id: "01",
    title: "Company",
    links: ["Home", "About Us", "Services", "Our Team"],
  },
  {
    id: "02",
    title: "Policy",
    links: ["Policies", "Contact", "FAQ"],
  },
  {
    id: "03",
    title: "Support",
    links: ["Account", "Support Center", "Feedback", "Accessibility"],
  },
];

export const users = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    password: "password123",
    contact: "+1234567890",
    about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    profileUrl: User1,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    password: "qwerty456",
    contact: "+1987654321",
    about: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    profileUrl: User2,
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michaeljohnson@example.com",
    password: "mypass789",
    contact: "+1122334455",
    about: "Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    profileUrl: User3,
  },
  {
    firstName: "Emily",
    lastName: "Jones",
    email: "emilyjones@example.com",
    password: "pass1234",
    contact: "+9876543210",
    about: "Duis aute irure dolor in reprehenderit in voluptate.",
    profileUrl: User4,
  },
  {
    firstName: "David",
    lastName: "Brown",
    email: "davidbrown@example.com",
    password: "davidpass",
    contact: "+1555666777",
    about: "Excepteur sint occaecat cupidatat non proident sunt in culpa.",
    profileUrl: User5,
  },
  {
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarahwilson@example.com",
    password: "sarahpass",
    contact: "+1123456789",
    about: "Sed ut perspiciatis unde omnis iste natus error sit.",
    profileUrl: User6,
  },
  {
    firstName: "Alexander",
    lastName: "Garcia",
    email: "alexander@example.com",
    password: "alex123",
    contact: "+1122334455",
    about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    profileUrl: User7,
  },
  {
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia@example.com",
    password: "sophia456",
    contact: "+1987654321",
    about: "Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    profileUrl: User8,
  },
  {
    firstName: "Ethan",
    lastName: "Lopez",
    email: "ethan@example.com",
    password: "ethanpass",
    contact: "+1123456789",
    about: "Duis aute irure dolor in reprehenderit in voluptate.",
    profileUrl: User9,
  },
];
